name: Release Tagged Images and Version

on:
  workflow_run:
    workflows: ["CI → Dev → Release (auto-tag if all pass)"]
    types:
      - completed

env:
  REGISTRY: ghcr.io
  IMAGE_BACKEND: ghcr.io/${{ github.repository_owner }}/example-application/backend-demo
  IMAGE_FRONTEND: ghcr.io/${{ github.repository_owner }}/example-application/frontend-demo

jobs:
  release:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    permissions:
      contents: write
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Read version from file
        id: version
        run: |
          VERSION=$(cat version)
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & Push Frontend Image
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          push: true
          tags: |
            ${{ env.IMAGE_FRONTEND }}:${{ steps.version.outputs.version }}
            ${{ env.IMAGE_FRONTEND }}:latest

      - name: Build & Push Backend Image
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          push: true
          tags: |
            ${{ env.IMAGE_BACKEND }}:${{ steps.version.outputs.version }}
            ${{ env.IMAGE_BACKEND }}:latest

      - name: Generate release notes
        id: notes
        uses: release-drafter/release-drafter@v5
        with:
          version: ${{ steps.version.outputs.version }}

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          name: v${{ steps.version.outputs.version }}
          tag_name: v${{ steps.version.outputs.version }}
          body: ${{ steps.notes.outputs.body }}
